### ISSUE TITLE
Activities API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#14]
## Description
This epic is a sub goal of the epic for Complete REST API and provides functionality surrounding students. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This API impacts all activity management module as without it students can't organize and activities or invite other students. We want to be able to manage create. We want to allow students to attend activities. We want to be able to post activities on activities feed. We should work on this soon after setting up Students API.

### Hypothesis
We must have Authentication, Activity Types, Activity Statuses, Campus Spots and Students API setup prior to this. The following is true by the end of this API

- [x] We can query/manage activities
- [x] We can choose an activity type for an activity. #13 
- [x] We can choose an activity status for an activity. #12 
- [x] We can choose a campus spot as a fixed spot for an activity. #11 
- [x] We can query/manage possible attendees of an activity

## Acceptance criteria and must have scope
In the end we need to have a collection of following endpoints:

- [x] #91 
- [x] #96 
- [x] #92 
- [x] #94 
- [x] #97 
- [x] #95 
- [x] #99 
- [x] #93
- [x] #98  
- [x] Documentation For Each Endpoint
- [x] Tests For Each Endpoint

## Stakeholders
None

## Timeline
3 weeks are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
This Epic has 3 stages:

1. First 7 starting days we will work on the base functionality of this API. 
2. Sub epics will begin and continue till 3 days before the deadline.
3. Remaining 3 days, after sub epics are complete, will be used to check each of their functionalities in combination for this API's endpoints e.g. **Get an activity's attendees** after `Students API` complete.
