### ISSUE TITLE
Student Connections API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#15]
## Description
This epic is a sub goal of the epic for Students API and provides functionality surrounding connections of students. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This API impacts all our unipal finder module as without this we can't create any connections for our project and we can't run matching algorithms. We want to be able to manage friend requests, friends and blocked users of a student. We want a two way relationship from the sending student to the receiving student and vice versa. We should work on this immediately after setting up Activities APIs.

### Hypothesis
We must have Students API setup prior to this. The following is true by the end of this API

- [x] We can manage friend requests for a student to multiple students
- [x] We can mange friends of a student
- [x] We can manage blocked users of a student

## Acceptance criteria and must have scope
In the end we need to have a collection of following endpoints:

- [x] #115 
- [x] #113
- [x] #116 
- [x] #114
- [x] #119
- [x] Documentation For Each Endpoint
- [x] Tests For Each Endpoint

## Stakeholders
None

## Timeline
2 weeks are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
> When a friend request is accepted we change the is_accepted to true but keep the record as long as the friend connection exists.
> 
> When a friendship is ended we delete the corresponding friend_request as well.

Since the merging of PR #118, we no longer need to manage friend requests and friends seperately and instead use a single student connections api to serve both
