### ISSUE TITLE
Friends API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#16]
## Description
This epic is a sub goal of the epic for Students API and provides functionality surrounding friends of students. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This API impacts all our unipal finder and memories feed modules as without this we can't show relevant memories on the feed and we can't run matching algorithms. We want to be able to manage friends of a student. We want a two way relationship from the initiating student to the accepting student and vice versa. We should work on this immediately after setting up Friend Requests API.

### Hypothesis
We must have Friend Requests and Students API setup prior to this. The following is true by the end of this API

- [ ] We can create friendships for a student
- [ ] We can delete friendships for a student
- [ ] We can update friendships for a student

## Acceptance criteria and must have scope
In the end we need to have a collection of following endpoints:

- [ ] GET All Friends (Temporary - For testing only)
- [ ] POST A New Friendship For A Student
- [ ] PATCH A Friendship For A Student
- [ ] DELETE A Friendship For A Student
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

## Stakeholders
None

## Timeline
2 weeks are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
The endpoints for this API were shifted inside #15, and closed in PR #120
