### ISSUE TITLE
[EPIC] Hangout Requests API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#17]
## Description
This epic is a sub goal of the epic for Students API and provides functionality surrounding connections of students. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This API impacts all our connections module as without this we have limited functionality to interact with other students in our project. We want to be able to manage hangout requests of a student. We should work on this immediately after setting up Friends API.

### Hypothesis
We must have Students API setup prior to this. The following is true by the end of this API

- [ ] We can create hangout requests for a student to multiple students
- [ ] We can delete hangout requests for a student
- [ ] We can update hangout requests for a student

## Acceptance criteria and must have scope
In the end we need to have a collection of following endpoints:

- [ ] GET All Hangout Requests (Temporary - For testing only)
- [ ] POST A New Hangout Request For A Student
- [ ] PATCH A Hangout Request For A Student
- [ ] DELETE A Hangout Request For A Student
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

## Stakeholders
None

## Timeline
2 weeks are needed to setup all the foundation, along with testing and documentation. No blockers expected.
