### ISSUE TITLE
[EPIC] Posts API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#18]
## Description
This epic is a sub goal of the epic for Complete REST API and provides functionality surrounding posting memories. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This API impacts our memories feed module as without posts the feed will show no data. We want to allow students to make new posts, optionally with some images or videos. We want to allow students to react to posts. We want to show all the reactions and uploads of a post. We should work on this immediately after setting up Hangout Requests API.

### Hypothesis
We must have Students and Reaction Types API setup prior to this. The following is true by the end of this API

- [ ] We can query/manage possible posts
- [ ] We can query/manage possible uploads of a post
- [ ] We can query/manage possible reactions of a post

## Acceptance criteria and must have scope
In the end we need to have a collection of following endpoints:

- [ ] GET All Posts
- [ ] GET A Single Post
- [ ] GET A Post's Uploads
- [ ] GET A Post's Reactions
- [ ] POST A New Post
- [ ] POST A New Reaction On A Post
- [ ] PATCH A Post
- [ ] PATCH A Reaction On A Post
- [ ] DELETE A Post
- [ ] DELETE A Reaction On A Post
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

## Stakeholders
None

## Timeline
5 weeks are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
This Epic has 3 stages:

1. First 7 starting days we will work on the base functionality of this API. 
2. Sub goals will begin and continue till 3 days before the deadline.
3. Remaining 3 days, after sub goals are complete, will be used to check each of their functionalities in combination for this API's endpoints e.g. **Get a post's reactions** after `Reaction Types API` complete.
