### ISSUE TITLE
[EPIC] Reaction Types API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#19]
## Description
This epic is a goal of the larger epic of Posts API and contains functionality for managing standard reactions in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to manage reaction types so that students can choose from them while reacting to posts.

### Hypothesis
The API must provide management of reaction types. This epic is considered complete when the following features are complete:

- [ ] Reaction Types Management
- [ ] Documentation
- [ ] Tests

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Reaction Types 
- [ ] GET A Single Reaction Type
- [ ] POST A New Reaction Type 🔒
- [ ] PATCH A Reaction Type 🔒
- [ ] DELETE A Reaction Type 🔒

*Note: 🔒 symbol indicates the route is protected and accessible to **admin** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
The possible reaction types could be:
* like
* love
* angry
* laugh
* sad
* boring
