### ISSUE TITLE
Authentication API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#2]
## Description
This epic is a goal of the larger epic of REST API and contains functionality for authentication in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This epic is a high impact goal as it provided the foundation for other API Epics.

### Hypothesis
The API must provide person authentication, request validation and request verification. These things must be true by the end:

- [ ] Private API KEY/OAuth2 verification.
- [x] Authorization token for each request.
- [x] Person authentication procedures.
- [x] Role based request access for each user.
- [x] Documentation
- [x] Tests

## Acceptance criteria and must have scope
In the end we need to have a collection of following endpoints:

- [x] SIGNUP A Student #29 
- [x] LOGIN A Student #28 
- [x] CHANGE Password Of A Student #30 
- [x] REFRESH Auth Token #58 
- [x] FORGOT Password Of A Student #31 

This API only focuses on auth related tasks for persons, requests and apps.

## Stakeholders
None

## Timeline
2 weeks are needed to setup all the foundation, along with testing and documentation. No blockers so far

**Comment by arafaysaleem** [comment]
Completed w/o an API KEY for now. Will implement the API KEY after #1
