### ISSUE TITLE
Teachers API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#21]
## Description
This epic is a goal of the larger epic of Complete REST API and contains functionality for teacher assignment in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to manage teachers so that classes can be created. We also want to query teachers so they can be displayed 
 along with their ratings, while generating timetables. We also want to query a teacher so it's overall rating can be updated each time a new review is added.

### Hypothesis
The API must provide management of teachers. This epic is considered complete when the following features are complete:

- [x] Teachers Management
- [x] Documentation
- [x] Tests

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [x] GET All Teachers 🔒
- [x] GET A Single Teacher 🔒
- [x] POST A New Teacher 🔒
- [x] PATCH A Teacher 🔒
- [x] DELETE A Teacher 🔒

*Note: 🔒 symbol indicates the route is protected and accessible to **admin** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
Completed in #170
