### ISSUE TITLE
[EPIC] Subjects API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#22]
## Description
This epic is a goal of the larger epic of Complete REST API and contains functionality for subject assignment in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to manage subjects so that classes can be created.

### Hypothesis
The API must provide management of subjects. This epic is considered complete when the following features are complete:

- [ ] Subjects Management
- [ ] Documentation
- [ ] Tests

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Subjects 🔒
- [ ] GET A Single Subject 🔒
- [ ] POST A New Subject 🔒
- [ ] PATCH A Subject 🔒
- [ ] DELETE A Subject 🔒

*Note: 🔒 symbol indicates the route is protected and accessible to **admin** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.
