### ISSUE TITLE
Timetables API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#26]
## Description
This epic is a sub goal of the epic for Complete REST API and provides functionality surrounding saving timetables. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This API impacts our timetable management module as without it we can't match students with overlaps. We want to allow students create multiple timetables, set one of them as active. We want to allow students to add classes in their timetables. We want to show all the timetables of a student. We want to show all the classes of a timetable. We should work on this immediately after setting up Classes API.

### Hypothesis
We must have Students and Classes API setup prior to this. The following is true by the end of this API

- [x] We can query/manage possible timetables
- [x] We can generate possible timetables from given classes
- [x] Documentation For Each Endpoint
- [x] Tests For Each Endpoint

## Acceptance criteria and must have scope
In the end we need to have a collection of following endpoints:

- [x] #212 
- [x] #213 
- [x] #218
- [x] #214 
- [x] #215 
- [x] #216 
- [x] #217 

## Stakeholders
None

## Timeline
3 weeks are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
Completed In #222
