### ISSUE TITLE
[EPIC] Timetable Share Rooms API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#27]
## Description
This epic is a sub goal of the epic for Complete REST API and provides functionality surrounding sharing timetables. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This API impacts our timetable management module as without it we can't share timetables with other students and find out overlaps. We want to allow students create multiple timetable sharing rooms, each with a fixed timetable to be matched against. We want to allow students to add other students in that room. We want to allow members of a room to share their own timetables. We want to show all the members of a room. We should work on this immediately after setting up Timetables API.

### Hypothesis
We must have Students and Timetables API setup prior to this. The following is true by the end of this API

- [ ] We can query/manage timetable share rooms (TSR) of a student
- [ ] We can query/manage possible members of a TSR

## Acceptance criteria and must have scope
In the end we need to have a collection of following endpoints:

- [ ] GET A Student's Timetable Share Rooms
- [ ] GET A Single Timetable Share Room
- [ ] GET A Single Timetable Share Room's Members
- [ ] POST A New Timetable Share Room
- [ ] POST A New Timetable Share Room Member
- [ ] PATCH A Timetable Share Room
- [ ] PATCH A Timetable Share Room Member
- [ ] DELETE A Timetable Share Room
- [ ] DELETE A Timetable Share Room Member
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

_**Note:**  Should load all classes for each TSR timetable_

## Stakeholders
None

## Timeline
5 weeks are needed to setup all the foundation, along with testing and documentation. No blockers expected.
