### ISSUE TITLE
Hobbies API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#3]
## Description
This epic is a goal of the larger epic of Students API and contains functionality for hobbies assignment in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to manage hobbies so that students can choose from them while creating accounts. These hobbies are also used to match similar students.

### Hypothesis
The API must provide management of hobbies. This epic is considered complete when the following features are complete:

- [x] Hobbies Management
- [x] Documentation
- [x] Tests

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [x] GET All Hobbies #39 
- [x] GET A Single Hobby #38 
- [x] POST A New Hobby 🔒 #32 
- [x] PATCH A Hobby 🔒 #36 
- [x] DELETE A Hobby 🔒 #37 

*Note: 🔒 symbol indicates the route is protected and accessible to **admin** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
Completed
