### ISSUE TITLE
Interests API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#4]
## Description
This epic is a goal of the larger epic of Students API and contains functionality for interests assignment in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to manage interests so that students can choose from them while creating accounts. These interests are also used to match similar students.

### Hypothesis
The API must provide management of interests. This epic is considered complete when the following features are complete:

- [x] Interests Management
- [x] Documentation
- [x] Tests

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [x] GET All Interests #43 
- [x] GET A Single Interest #42 
- [x] POST A New Interest 🔒 #33 
- [x] PATCH A Interest 🔒 #40 
- [x] DELETE A Interest 🔒 #41 

*Note: 🔒 symbol indicates the route is protected and accessible to **admin** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
Completed
