### ISSUE TITLE
Student Statuses API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#5]
## Description
This epic is a goal of the larger epic of Students API and contains functionality for student status assignment in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to manage student statuses so that students can choose from them while operating their account. These student statuses are also used to match similar students.

### Hypothesis
The API must provide management of student statuses. This epic is considered complete when the following features are complete:

- [x] Student Statuses Management
- [x] Documentation
- [x] Tests

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [x] GET All Student Statuses #53 
- [x] GET A Single Student Status #54 
- [x] POST A New Student Status 🔒 #52 
- [x] PATCH A Student Status 🔒 #56 
- [x] DELETE A Student Status 🔒 #55 

*Note: 🔒 symbol indicates the route is protected and accessible to **admin** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
The possible student statuses could be:
* looking for friends
* looking for transport
* looking for help
* looking for food

**Comment by arafaysaleem** [comment]
Completed
