### ISSUE TITLE
[EPIC] Universities API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#6]
## Description
This epic is a goal of the larger epic of Students API and contains functionality for university assignment in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to manage universities so that students can choose from them while creating their account. These student universities are also used to match similar students.

### Hypothesis
The API must provide management of universities. This epic is considered complete when the following features are complete:

- [ ] Universities Management
- [ ] Documentation
- [ ] Tests

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Universities
- [ ] GET A Single University
- [ ] POST A New University 🔒
- [ ] PATCH A University 🔒
- [ ] DELETE A University 🔒

*Note: 🔒 symbol indicates the route is protected and accessible to **admin** only*

## Stakeholders
None

## Timeline
1 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.
