### ISSUE TITLE
Campuses API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#7]
## Description
This epic is a goal of the larger epic of Universities API and contains functionality for campus management in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to manage campuses so that students can choose from them while creating their account and classrooms can be setup. These campuses are also used to match similar students.

### Hypothesis
The API must provide management of campuses. This epic is considered complete when the following features are complete:

- [x] Campuses Management
- [x] Documentation
- [x] Tests

## Acceptance criteria and must have scope
We must have Authentication API and Universities API setup prior to this. In the end we need to have a collection of following endpoints:

- [x] GET All Campuses #44 
- [x] GET A Single Campus #45 
- [x] POST A New Campus 🔒 #34 
- [x] PATCH A Campus 🔒 #47 
- [x] DELETE A Campus 🔒 #46 

*Note: 🔒 symbol indicates the route is protected and accessible to **admin** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
Completed
