### ISSUE TITLE
Programs API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#8]
## Description
This epic is a goal of the larger epic of Universities API and contains functionality for programs management in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to manage programs so that students can choose from them while creating their account and classes can be setup. These programs are also used to match similar students.

### Hypothesis
The API must provide management of programs. This epic is considered complete when the following features are complete:

- [x] Programs Management
- [x] Documentation
- [x] Tests

## Acceptance criteria and must have scope
We must have Authentication API and Universities API setup prior to this. In the end we need to have a collection of following endpoints:

- [x] GET All Programs #48 
- [x] GET A Single Program #49 
- [x] POST A New Program 🔒 #35 
- [x] PATCH A Program 🔒 #51 
- [x] DELETE A Program 🔒 #50 

*Note: 🔒 symbol indicates the route is protected and accessible to **admin** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
Completed
