### ISSUE TITLE
Students API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/UniPal-Backend#9]
## Description
This epic is a sub goal of the epic for Complete REST API and provides functionality surrounding students. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This API impacts all our modules as without students we can't create timetables, activities or any connections for our project and we can't proceed. We want to be able to manage activities. We want to build and search connections. We want to be able to post memories. We want to allow generating and sharing timetables. We should work on this immediately after setting up Preferences APIs.

### Hypothesis
We must have Authentication, Hobbies, Interests, Universities, Campuses, Programs and User Statuses API setup prior to this. The following is true by the end of this API

- [x] We can query/manage possible profile of a student
- [x] We can query/manage possible organized activities of a student #14 
- [x] We can query/manage possible saved activities of a student #14 
- [x] We can query/manage possible attending activities of a student #14 

## Acceptance criteria and must have scope
In the end we need to have a collection of following endpoints:

- [x] GET All Students #67 
- [x] #105 
- [x] #106 
- [x] #107 
- [x] GET A Single Student #68 
- [x] PATCH A Student #69 
- [x] DELETE A Student #70 
- [x] Documentation For Each Endpoint
- [x] Tests For Each Endpoint

## Stakeholders
None

## Timeline
5 weeks are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
This Epic has 3 stages:

1. First 7 starting days we will work on the base functionality of this API. 
2. Sub epics will begin and continue till 3 days before the deadline.
3. Remaining 3 days, after sub epics are complete, will be used to check each of their functionalities in combination for this API's endpoints e.g. **Get a student's activities** after `Activities API` complete.

**Comment by arafaysaleem** [comment]
Merging of #222 completed this epic, after all related relevant APIs were finished and the combined functionality was tested.
